CREATE TABLE IF NOT EXISTS role_permissions (
  role TEXT NOT NULL,
  permission TEXT NOT NULL,
  allowed BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (role, permission)
);

INSERT INTO role_permissions (role, permission, allowed) VALUES
  ('student', 'submit_thesis', TRUE),
  ('student', 'review_academic', FALSE),
  ('student', 'library_intake', FALSE),
  ('student', 'director_approval', FALSE),
  ('student', 'view_all_submissions', FALSE),
  ('student', 'manage_users', FALSE),
  ('student', 'manage_roles', FALSE),
  ('student', 'configure_system', FALSE),
  ('reviewer', 'submit_thesis', FALSE),
  ('reviewer', 'review_academic', TRUE),
  ('reviewer', 'library_intake', FALSE),
  ('reviewer', 'director_approval', FALSE),
  ('reviewer', 'view_all_submissions', FALSE),
  ('reviewer', 'manage_users', FALSE),
  ('reviewer', 'manage_roles', FALSE),
  ('reviewer', 'configure_system', FALSE),
  ('library_staff', 'submit_thesis', FALSE),
  ('library_staff', 'review_academic', FALSE),
  ('library_staff', 'library_intake', TRUE),
  ('library_staff', 'director_approval', FALSE),
  ('library_staff', 'view_all_submissions', TRUE),
  ('library_staff', 'manage_users', FALSE),
  ('library_staff', 'manage_roles', FALSE),
  ('library_staff', 'configure_system', FALSE),
  ('director', 'submit_thesis', FALSE),
  ('director', 'review_academic', FALSE),
  ('director', 'library_intake', FALSE),
  ('director', 'director_approval', TRUE),
  ('director', 'view_all_submissions', TRUE),
  ('director', 'manage_users', FALSE),
  ('director', 'manage_roles', FALSE),
  ('director', 'configure_system', FALSE),
  ('admin', 'submit_thesis', FALSE),
  ('admin', 'review_academic', FALSE),
  ('admin', 'library_intake', FALSE),
  ('admin', 'director_approval', FALSE),
  ('admin', 'view_all_submissions', FALSE),
  ('admin', 'manage_users', TRUE),
  ('admin', 'manage_roles', TRUE),
  ('admin', 'configure_system', TRUE)
ON CONFLICT (role, permission) DO NOTHING;
